version: "3"

services:
  advertising_app:
    build: advertising_app
    depends_on:
      advertising_db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - spring-postgres
  advertising_db:
    image: postgres:12.2
    container_name: advertising_db
    restart: always
    volumes:
      - ./advertising_db/schema-advertising.sql:/docker-entrypoint-initdb.d/schema-advertising.sql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=advertising
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  db-data:
networks:
  spring-postgres: